try {
  require('foo')
} catch (e) {
  console.error(e)
}